### ISSUE TITLE
Missing local setup instructions step

### ISSUE THREAD

**Issue by paulds-explore** [microsoft/showwhy#182]
I am trying to test showwhy locally.

All containers are up and I am simply trying to run the packaged COVID example end-to-end.

When it comes to estimating the causal effects there is an API error:

```
502 bad gateway for http://localhost:81/api/getnumberofexecutions?code=local-docker-key
```

What needs to be set in `javascript/webapp/.env` for local development?

**Comment by paulds-explore** [comment]
@dayesouza, thanks for the clarification. Yes, it is an M1. I guess for now I'll try do this within a dev container. Please reach out if you need anyone to test this natively an M1.

**Comment by emrekiciman** [comment]
@dayesouza, should we add a note about this M1 restriction to the README?

**Comment by dayesouza** [comment]
@emrekiciman Yes, I'll add it. Even with the Azure Functions removed we still have problems with M1 because of Tensorflow

**Comment by gwendorff** [comment]
Mac M1 will be supported any time soon?

**Comment by jprussoibanez** [comment]
Hi all, I am able to run the dockers on a M1 Mac with some hacky workaround (not a final solution for the issue though). I’m posting the solution as it may help others (until Tensorflow library fully support running amd64 dockers in M1 Mac), and hopefully it can trigger some better solution discussions as well.

### Problem context

1. **Tensorflow and Jax library dependencies**
    1. ShowWhy has dependencies on Tensorflow and indirectly on Jax library not fully supported on Mac M1 as explained on [tensorflow issue](https://github.com/tensorflow/tensorflow/issues/52972) and [jax issue](https://github.com/google/jax/issues/13608).
    2. The general temporal fix suggested is to [build from source Tensorflow and Jax without AVX instructions.](https://github.com/tensorflow/tensorflow/issues/52972#issuecomment-962595314)
2. **Sklearn deprecated dependency**
    1. There is also a dependency to deprecated [sklearn (0.0.post1)](https://pypi.org/project/sklearn/) on the current [poetry lock file](https://github.com/microsoft/showwhy/blob/9c7c3e3549ceed59a6fb6fc4409729236714f124/python/backend/poetry.lock#L5705) (not sure the reason, as it’s not explicitly added on the `poetry.toml` file).
    2. This also turned into a problem when installing dependencies locally with poetry (at least on M1 Mac). Anyways, my understanding are projects should only have dependencies on the new [scikit-learn](https://pypi.org/project/scikit-learn/) version.
  
### Workaround

I’m sharing my [fork commit to see the full changes.](https://github.com/microsoft/showwhy/commit/5cf4bcb2586840b9ff5679789996428758f1f78e) You’ll see it’s not many changes, but is not a final solution to the issue (as it tinkers with library versions).

Probably the best solution is to build from sources Tensorflow and Jax libraries but is a more complex and effortful solution, so here is my explanation for a quicker (but more hacky) workaround approach.

1. **Tensorflow**: Building the TensorFlow locally may take some time, so there are already some people that build and publish their own [versions](https://tf.novaal.de/)(unfortunately couldn’t find a v2.9, so I need to downgrade to v2.8 on my fix).
*Disclaimer: Be careful on using this type of library cause there are not official and may have some harmful code (if you don’t build it yourself).*
    1. Find the [reinstallation of Tensorflow the library on this line of the docker file](https://github.com/microsoft/showwhy/commit/5cf4bcb2586840b9ff5679789996428758f1f78e#diff-bd8fb6d051bfc9685cffcfe31caba4f4d1a6459e08d74982a9e14e3830465a04R44) (after all poetry original installation is in place).
2. **Jax**: Jax has the [same issue](https://github.com/google/jax/issues/13608) on newer versions, though it can be fixed using early versions of the library. I just reinstall with poetry jax and jaxlib without dependencies (this is also brittle as can break dependencies in subtle ways, but seems to work with the current version so far).
    1. Find the [reinstallation of the jax and jaxlib library on this line of the docker file](https://github.com/microsoft/showwhy/commit/5cf4bcb2586840b9ff5679789996428758f1f78e#diff-bd8fb6d051bfc9685cffcfe31caba4f4d1a6459e08d74982a9e14e3830465a04R45).
    *Note: It’s important to use the `—no-deps`, if not poetry will reinstall other dependencies and the fix won’t work unfortunately.*
3. **Sklearn deprecated dependency**: I just [remove manually the sklearn dependency as shown here](https://github.com/microsoft/showwhy/commit/5cf4bcb2586840b9ff5679789996428758f1f78e#diff-0c99bf616f1bed26455a0487397da460434a20492a98f0c3d3128386d6e905b3L5705). This is probably something that should be fixed directly on ShowWhy `poetry.lock` file though.

### Devcontainers

VSCode also has the great feature of using [devcontainers for developing on multiple platforms.](https://code.visualstudio.com/docs/devcontainers/containers)

I add this [devcontainers support](https://github.com/microsoft/showwhy/commit/81a83b79eec75307d55b3e20497cf563650bd3e8) (reusing the fix) to do local development & debugging on Mac M1 if that helps too.

Hope to hear some more final and better solutions to this issue!
