### ISSUE TITLE
Incopleatre 'just get going' instructions

### ISSUE THREAD

**Issue by elikling** [microsoft/showwhy#253]
The set up instructions assume a high level of technical competance as an application developer. Peopel like myself who are mainly staticticians with some knowledge of UNIX and Python will (am) straggle. for istnace it took me time to realize that one needed to 
```
git clone "https://github.com/microsoft/showwhy"
cd showwhy
```
before 
```
sudo yarn install
sudo yarn build
```

even so I get error messages I cannot handle. I tired UBUNTU18 and UBUNTU20 and spend two days trying differnet fixes and instalations of supporting software - I have a feeling I am missing something - is there a website where I can just try it or is there a simpel "install" I can run

eli.kling@avanade.com
https://www.linkedin.com/in/elikling/

**Comment by darthtrevino** [comment]
Hey @elikling, I'm just noticing your comment here, I apologize for the delay!

Are you running on Ubuntu directly or in WSL on a Windows machine? If you just want to fire up the application to try it out, I'd recommend avoiding yarn and using Docker directly:

`docker-compose --profile all up`

You'll need to install [Docker](https://www.docker.com/) - that website has a downloadable for Windows, or you can follow the Linux instructions [here](https://docs.docker.com/engine/install/ubuntu/)

**Comment by emrekiciman** [comment]
@darthtrevino , is your recommendation the same as the "local deployment" instructions here? https://github.com/microsoft/showwhy/blob/main/docs/deployment/LOCAL_DEPLOY.md

**Comment by darthtrevino** [comment]
No, that's a bit heavyweight of a solution for running locally. That's more for testing out the infra. I've added some top-level notes in the README that recommend docker explicitly for just firing up the app.

**Comment by elikling** [comment]
I tried following the instruction above both on a windows VM and an Ubuntu and am still encountering issues. I consulted a Kubernetes expert and also he could not solve the issues. We will assign one of our AI engineering grands to try and figure out how to get this going.
