### ISSUE TITLE
Frontend exited with code 1

### ISSUE THREAD

**Issue by vdemchenko3** [microsoft/showwhy#380]
Hello! 

I downloaded the repo locally and ran `docker-compose --profile all up` and am getting an `exited with code 1` error on the frontend.  Please see attached images. 
<img width="642" alt="Screenshot 2023-01-31 at 10 03 09" src="https://user-images.githubusercontent.com/15091189/215730035-0227f8f4-a81c-4b98-8a83-7c12e2e8aba4.png">
<img width="878" alt="Screenshot 2023-01-31 at 10 03 26" src="https://user-images.githubusercontent.com/15091189/215730042-6b18c616-0203-4452-96f7-390b3aa453c7.png">

Thanks in advance for the help!

**Comment by monik182** [comment]
Hi @vdemchenko3 this issue was solved last week.
