### ISSUE TITLE
Has anyone successfully build the app in Azure Portal using the AKS ARM Template ?

### ISSUE THREAD

**Issue by hungha90** [microsoft/showwhy#439]
Hi, 

I am trying to deploy the app on Azure using the template but during the deployment process I got this error message 

> {
  "code": "DeploymentFailed",
  "target": "/subscriptions/f5e981f8-18dd-4538-adbd-e9428e2bd81d/resourceGroups/show_why_deploy/providers/Microsoft.Resources/deployments/helmDeployment",
  "message": "At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-deployment-operations for usage details.",
  "details": [
    {
      "code": "ResourceDeploymentFailure",
      "target": "/subscriptions/f5e981f8-18dd-4538-adbd-e9428e2bd81d/resourceGroups/show_why_deploy/providers/Microsoft.Resources/deployments/helmScripts",
      "message": "The resource write operation failed to complete successfully, because it reached terminal provisioning state 'Failed'.",
      "details": [
        {
          "code": "DeploymentFailed",
          "message": "At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-deployment-operations for usage details.",
          "details": [
            {
              "code": "Conflict",
              "message": "{\r\n  \"status\": \"failed\",\r\n  \"error\": {\r\n    \"code\": \"ResourceDeploymentFailure\",\r\n    \"message\": \"The resource write operation failed to complete successfully, because it reached terminal provisioning state 'failed'.\",\r\n    \"details\": [\r\n      {\r\n        \"code\": \"DeploymentScriptError\",\r\n        \"message\": \"The provided script failed with multiple errors. First error:\\r\\nConnecting to get.helm.sh (152.199.39.108:443). Please refer to https://aka.ms/DeploymentScriptsTroubleshoot for more deployment script information.\",\r\n        \"details\": [\r\n          {\r\n            \"code\": \"DeploymentScriptError\",\r\n            \"message\": \"Connecting to get.helm.sh (152.199.39.108:443)\"\r\n          },\r\n          {\r\n            \"code\": \"DeploymentScriptError\",\r\n            \"message\": \"saving to 'helm.tgz'\"\r\n          },\r\n          {\r\n            \"code\": \"DeploymentScriptError\",\r\n            \"message\": \"helm.tgz 100% |********************************| 13.8M 0:00:00 ETA\"\r\n          },\r\n          {\r\n            \"code\": \"DeploymentScriptError\",\r\n            \"message\": \"'helm.tgz' saved\"\r\n          },\r\n          {\r\n            \"code\": \"DeploymentScriptError\",\r\n            \"message\": \"Downloading client to \\\"/usr/local/bin/kubectl\\\" from \\\"https://storage.googleapis.com/kubernetes-release/release/v1.29.3/bin/linux/amd64/kubectl\\\"\"\r\n          },\r\n          {\r\n            \"code\": \"DeploymentScriptError\",\r\n            \"message\": \"Please ensure that /usr/local/bin is in your search PATH, so the `kubectl` command can be found.\"\r\n          },\r\n          {\r\n            \"code\": \"DeploymentScriptError\",\r\n            \"message\": \"Downloading client to \\\"/tmp/tmpu3_qvndu/kubelogin.zip\\\" from \\\"https://github.com/Azure/kubelogin/releases/download/v0.1.1/kubelogin.zip\\\"\"\r\n          },\r\n          {\r\n            \"code\": \"DeploymentScriptError\",\r\n            \"message\": \"Please ensure that /usr/local/bin is in your search PATH, so the `kubelogin` command can be found.\"\r\n          },\r\n          {\r\n            \"code\": \"DeploymentScriptError\",\r\n            \"message\": \"Pulled: ghcr.io/microsoft/showwhy/causal-services:0.3.0\"\r\n          },\r\n          {\r\n            \"code\": \"DeploymentScriptError\",\r\n            \"message\": \"Digest: sha256:ef0f374a74ccc57419b8b6aeedc4fa31ca9b66c854504a5fdb30e215ed270ce0\"\r\n          },\r\n          {\r\n            \"code\": \"DeploymentScriptError\",\r\n            \"message\": \"Error: failed pre-install: timed out waiting for the condition\"\r\n          }\r\n        ]\r\n      }\r\n    ]\r\n  }\r\n}"
            }
          ]
        }
      ]
    }
  ]
} >

> {"code":"DeploymentFailed","target":"/subscriptions/f5e981f8-18dd-4538-adbd-e9428e2bd81d/resourceGroups/show_why_deploy/providers/Microsoft.Resources/deployments/helmDeployment","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-deployment-operations for usage details.","details":[{"code":"ResourceDeploymentFailure","target":"/subscriptions/f5e981f8-18dd-4538-adbd-e9428e2bd81d/resourceGroups/show_why_deploy/providers/Microsoft.Resources/deployments/helmScripts","message":"The resource write operation failed to complete successfully, because it reached terminal provisioning state 'Failed'.","details":[{"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-deployment-operations for usage details.","details":[{"code":"Conflict","message":"{\r\n  \"status\": \"failed\",\r\n  \"error\": {\r\n    \"code\": \"ResourceDeploymentFailure\",\r\n    \"message\": \"The resource write operation failed to complete successfully, because it reached terminal provisioning state 'failed'.\",\r\n    \"details\": [\r\n      {\r\n        \"code\": \"DeploymentScriptError\",\r\n        \"message\": \"The provided script failed with multiple errors. First error:\\r\\nConnecting to get.helm.sh (152.199.39.108:443). Please refer to https://aka.ms/DeploymentScriptsTroubleshoot for more deployment script information.\",\r\n        \"details\": [\r\n          {\r\n            \"code\": \"DeploymentScriptError\",\r\n            \"message\": \"Connecting to get.helm.sh (152.199.39.108:443)\"\r\n          },\r\n          {\r\n            \"code\": \"DeploymentScriptError\",\r\n            \"message\": \"saving to 'helm.tgz'\"\r\n          },\r\n          {\r\n            \"code\": \"DeploymentScriptError\",\r\n            \"message\": \"helm.tgz 100% |********************************| 13.8M 0:00:00 ETA\"\r\n          },\r\n          {\r\n            \"code\": \"DeploymentScriptError\",\r\n            \"message\": \"'helm.tgz' saved\"\r\n          },\r\n          {\r\n            \"code\": \"DeploymentScriptError\",\r\n            \"message\": \"Downloading client to \\\"/usr/local/bin/kubectl\\\" from \\\"https://storage.googleapis.com/kubernetes-release/release/v1.29.3/bin/linux/amd64/kubectl\\\"\"\r\n          },\r\n          {\r\n            \"code\": \"DeploymentScriptError\",\r\n            \"message\": \"Please ensure that /usr/local/bin is in your search PATH, so the `kubectl` command can be found.\"\r\n          },\r\n          {\r\n            \"code\": \"DeploymentScriptError\",\r\n            \"message\": \"Downloading client to \\\"/tmp/tmpu3_qvndu/kubelogin.zip\\\" from \\\"https://github.com/Azure/kubelogin/releases/download/v0.1.1/kubelogin.zip\\\"\"\r\n          },\r\n          {\r\n            \"code\": \"DeploymentScriptError\",\r\n            \"message\": \"Please ensure that /usr/local/bin is in your search PATH, so the `kubelogin` command can be found.\"\r\n          },\r\n          {\r\n            \"code\": \"DeploymentScriptError\",\r\n            \"message\": \"Pulled: ghcr.io/microsoft/showwhy/causal-services:0.3.0\"\r\n          },\r\n          {\r\n            \"code\": \"DeploymentScriptError\",\r\n            \"message\": \"Digest: sha256:ef0f374a74ccc57419b8b6aeedc4fa31ca9b66c854504a5fdb30e215ed270ce0\"\r\n          },\r\n          {\r\n            \"code\": \"DeploymentScriptError\",\r\n            \"message\": \"Error: failed pre-install: timed out waiting for the condition\"\r\n          }\r\n        ]\r\n      }\r\n    ]\r\n  }\r\n}"}]}]}]} 

Please check and tell me how can I fix it

Thank you

**Comment by dayesouza** [comment]
Hi!
I just tested and it worked fine on my Azure.
Did you used the Deploy to Azure button? It seems like a  temporary helm problem maybe?

**Comment by hungha90** [comment]
> Hi! I just tested and it worked fine on my Azure. Did you used the Deploy to Azure button? It seems like a temporary helm problem maybe?

Hi @dayesouza , yes I used the deploy to Azure button (right in this link: https://github.com/microsoft/showwhy?tab=readme-ov-file#deployment ) but I got error when deploying helm (please see the image in attachment) 
![z5304968324907_9bfabbc835edd1c51eec8480375e3128](https://github.com/microsoft/showwhy/assets/130202082/ba127e09-03b9-4dd3-a0ec-7daf4d67f3a6)

Do you have any suggestion to fix that ?

Thank you

**Comment by dayesouza** [comment]
@hungha90 , By the 'conflict' it's written there, can you verify that it's not creating any resource name that you already have? 
In the first message is it the Error details or Operation details?

**Comment by hungha90** [comment]
Hi @dayesouza ,

I just tried to deploy again but still got the same error

![1](https://github.com/microsoft/showwhy/assets/130202082/d9002b81-54f1-432a-88d2-141f6bdaec05)
![2](https://github.com/microsoft/showwhy/assets/130202082/344bd057-4f40-4d2d-8480-6bd52287372a)

And when I click on "Error Detail", I got this 
`{"code":"DeploymentFailed","target":"/subscriptions/f5e981f8-18dd-4538-adbd-e9428e2bd81d/resourceGroups/new_showwhy_resourcegroup/providers/Microsoft.Resources/deployments/helmDeployment","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-deployment-operations for usage details.","details":[{"code":"ResourceDeploymentFailure","target":"/subscriptions/f5e981f8-18dd-4538-adbd-e9428e2bd81d/resourceGroups/new_showwhy_resourcegroup/providers/Microsoft.Resources/deployments/helmScripts","message":"The resource write operation failed to complete successfully, because it reached terminal provisioning state 'Failed'.","details":[{"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-deployment-operations for usage details.","details":[{"code":"Conflict","message":"{\r\n  \"status\": \"failed\",\r\n  \"error\": {\r\n    \"code\": \"ResourceDeploymentFailure\",\r\n    \"message\": \"The resource write operation failed to complete successfully, because it reached terminal provisioning state 'failed'.\",\r\n    \"details\": [\r\n      {\r\n        \"code\": \"DeploymentScriptError\",\r\n        \"message\": \"The provided script failed with multiple errors. First error:\\r\\nConnecting to get.helm.sh (152.199.39.108:443). Please refer to https://aka.ms/DeploymentScriptsTroubleshoot for more deployment script information.\",\r\n        \"details\": [\r\n          {\r\n            \"code\": \"DeploymentScriptError\",\r\n            \"message\": \"Connecting to get.helm.sh (152.199.39.108:443)\"\r\n          },\r\n          {\r\n            \"code\": \"DeploymentScriptError\",\r\n            \"message\": \"saving to 'helm.tgz'\"\r\n          },\r\n          {\r\n            \"code\": \"DeploymentScriptError\",\r\n            \"message\": \"helm.tgz 100% |********************************| 13.8M 0:00:00 ETA\"\r\n          },\r\n          {\r\n            \"code\": \"DeploymentScriptError\",\r\n            \"message\": \"'helm.tgz' saved\"\r\n          },\r\n          {\r\n            \"code\": \"DeploymentScriptError\",\r\n            \"message\": \"Downloading client to \\\"/usr/local/bin/kubectl\\\" from \\\"https://storage.googleapis.com/kubernetes-release/release/v1.29.3/bin/linux/amd64/kubectl\\\"\"\r\n          },\r\n          {\r\n            \"code\": \"DeploymentScriptError\",\r\n            \"message\": \"Please ensure that /usr/local/bin is in your search PATH, so the `kubectl` command can be found.\"\r\n          },\r\n          {\r\n            \"code\": \"DeploymentScriptError\",\r\n            \"message\": \"Downloading client to \\\"/tmp/tmp6yn0u74p/kubelogin.zip\\\" from \\\"https://github.com/Azure/kubelogin/releases/download/v0.1.1/kubelogin.zip\\\"\"\r\n          },\r\n          {\r\n            \"code\": \"DeploymentScriptError\",\r\n            \"message\": \"Please ensure that /usr/local/bin is in your search PATH, so the `kubelogin` command can be found.\"\r\n          },\r\n          {\r\n            \"code\": \"DeploymentScriptError\",\r\n            \"message\": \"Pulled: ghcr.io/microsoft/showwhy/causal-services:0.3.0\"\r\n          },\r\n          {\r\n            \"code\": \"DeploymentScriptError\",\r\n            \"message\": \"Digest: sha256:ef0f374a74ccc57419b8b6aeedc4fa31ca9b66c854504a5fdb30e215ed270ce0\"\r\n          },\r\n          {\r\n            \"code\": \"DeploymentScriptError\",\r\n            \"message\": \"Error: failed pre-install: timed out waiting for the condition\"\r\n          }\r\n        ]\r\n      }\r\n    ]\r\n  }\r\n}"}]}]}]}`

![3](https://github.com/microsoft/showwhy/assets/130202082/84016b86-186d-4644-8370-184c6996a715)

And when I click on "Operation Details", I got this 
![4](https://github.com/microsoft/showwhy/assets/130202082/7a9aee2e-6683-4d50-8289-4aca8b4e302e)

![5](https://github.com/microsoft/showwhy/assets/130202082/227fdce7-60a0-4db9-a3b7-7cbe7ddfef2d)

I do not know how to fix it

Do you have any suggestion?

Thank you

**Comment by dayesouza** [comment]
@hungha90 I had a similar problem when deploying with a DNS name that already existed for that region.... but my error was exactly saying that.
If it's not it, I wonder if it's any limitation on your azure subscription or account?

**Comment by hungha90** [comment]
> @hungha90 I had a similar problem when deploying with a DNS name that already existed for that region.... but my error was exactly saying that. If it's not it, I wonder if it's any limitation on your azure subscription or account?

Hi @dayesouza  it looks like the issue got resolved . I have succussed in deploying the tool in Azure. Thank you for your concern

**Comment by MujunguMuseru** [comment]
@hungha90 and @dayesouza is showwhy working for you right now? i have successfully deployed the app but i cant get the URL to work? could you assist?

**Comment by dayesouza** [comment]
> [@hungha90](https://github.com/hungha90) and [@dayesouza](https://github.com/dayesouza) is showwhy working for you right now? i have successfully deployed the app but i cant get the URL to work? could you assist?

Just tried it and it worked. What's happening with your URL?

**Comment by MujunguMuseru** [comment]
@dayesouza , I finally got it to work. I was using the wrong URL, but it works right now. Thanks for the quick response.
